### ISSUE TITLE
git mv support?

### ISSUE THREAD

**Issue by swrobel** [titoBouzout/SideBarGit#11]
Are there plans to add `git mv` (move) support?

**Comment by attenzione** [comment]
+1

**Comment by titoBouzout** [comment]
Give a complete example command

**Comment by attenzione** [comment]
Right click on file/folder in sidebar to allow use "git mv" to rename file/folder instead of using os/ide rename. Because sometimes git doesn't recognise renaming and deletes and add new files to repository instead of renaming it.

**Comment by titoBouzout** [comment]
can you please provide an example

**Comment by attenzione** [comment]
Which points is not clear to your? 
I can rename file or folder using 2 methods, via mv or git mv, first is standard sublime renaming in sidebar, second could be part of this package

**Comment by attenzione** [comment]
Awesome. Thanx!

On Tue, Mar 8, 2016, 04:31 Tito <notifications@github.com> wrote:

> Closed #11 <https://github.com/titoBouzout/SideBarGit/issues/11> via
> 18a1328
> <https://github.com/titoBouzout/SideBarGit/commit/18a1328039b83f5a8491037b879b0890329dd73f>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/titoBouzout/SideBarGit/issues/11#event-581130362>.
>
-- 

Regards, Sergey M.
