### ISSUE TITLE
Git Pull problem

### ISSUE THREAD

**Issue by Frogli** [titoBouzout/SideBarGit#27]
I ran up a problem using the Git Pull command in Sublime Text using this plugin. The error below is shown:
/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory

A git pull from the terminal goes just fine.

How can I resolve this problem?

I am using Yosimithe 10.10.2, git 1.9.3, Sublime Text 3 build 3065

Thanks in advance for looking in to this problem.

grtz Henk

**Comment by titoBouzout** [comment]
This is unrelated to the package, IDK how to fix the problem, maybe adding git to the PATH ? using another git installation?

**Comment by Frogli** [comment]
Thanks for giving this hints. I did another google search and found a solution which works for me at the link: http://goo.gl/fD3rnY

In short:  Edit your git-pull file and add this line on top of it (just after the comment block)
```
PATH="$(dirname $0):$PATH"
```

**Comment by titoBouzout** [comment]
cool, glad you found a solution
