### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by Eithos** [titoBouzout/SideBarGit#30]
Hello!

First time posting on github and only just a day into learning about git, so I apologize if I'm posting in the wrong place or am otherwise mistaken in what I'm going to say. I was playing with SideBarGit and am very pleased so far with not having to exit out of Sublime to perform all these git tasks. Very cool.

So far I've only been playing around with a dummy repository to get a feel for how git works, and something weird happened. It's my understanding that git only commits files/changes that have been staged and that this can be a useful mechanism when, for example, one has a drawn-out session and wishes to commit changes in separate chunks. 

Here's what confuses me: If I modify a file, create a new one and only add that one to the staging area, I expect the commit to only take the new file into consideration without committing the modifications from the other file. This works as expected inside of the cmd prompt, as can be seen with git status. I tried the same thing with SideBarGit using the 'commit...' command and all changes were committed (whether or not it was staged), which is... a bit frustrating. Is there any way around this or have I perhaps not located the correct widget to achieve this effect?

Thanks!

**Comment by titoBouzout** [comment]
I'm not sure if I understand your problem, what I see is expected to me, but because I dont make use of the staging area (I also don't know how it works). This is what I do.

1. Right click a folder Select -> Git -> Commit..
2. The following command will run on cmd with the selected folder as CWD:  "git commit -m 'my commit message' -- ."

**Comment by FoxyAntho** [comment]
@titoBouzout The staging area are the files which are ready to be commit-ed ( the files you add with `git add` ) :smiley: 

I had the same problem, imagine this tree :
```
project/
     file_1
     file_2
     file_3
```
Now modify all the files. But **only** mark `file_1` and `file_2` as staged ( `git add` )

I want to commit the two files with one single commit, so, right click the parent-folder ( `project` ) then perform `Git -> Commit...`. Surprisingly **all** the three files where added and commit-ed, even if I had only selected two.

I agree with your second point, the `git commit .` <-- with the dot, will commit all, but the command's name is a bit frustrating. When we perform a `git commit`, it'll only commit the staging area, not everything.

Hope it could help.

**Comment by titoBouzout** [comment]
Many thanks I got it and is now fixed
