### ISSUE TITLE
Is it possible to customize a syntax for a Git command?

### ISSUE THREAD

**Issue by jfcherng** [titoBouzout/SideBarGit#31]
For example, I have a `git-blame` syntax, which is downloaded from [here](https://github.com/kemayo/sublime-text-git/tree/master/syntax), 
but I do `Context menu >> Git >> Blame`, which gives `Diff` as the syntax.

Any idea to customize this?

**Comment by titoBouzout** [comment]
now fixed took a while :)

**Comment by jfcherng** [comment]
Comfirmed. Thanks for your work :+1:
