### ISSUE TITLE
Supress the output to tabs?

### ISSUE THREAD

**Issue by doktordirk** [titoBouzout/SideBarGit#35]
"by matze79dd on Mon Jul 27, 2015 2:54 pm

Hi.

Is it possible to supress the output to tabs? i currently use Add & Commit & Push a lot throughout the day and everytime two new tabs are opened with the output. this leads to me having to close quite a lot of tabs per day. so it would be nice to have an option to supress the opening of tabs or at least have the output in a single tab and append the content every time.

Great plugin otherwise :)"
-------------------------------------------------------

same here (including last comment). i'll add it here so it won't be forgotten.
cheers dd

**Comment by webcaetano** [comment]
+1

Same problem.
I do prefer using cmd , and git desktop because of this.

When you press Ctrl+W to close this new tab , it don't bring you back to the page here you was

**Comment by titoBouzout** [comment]
It would be nice(to be able to configure) to open a tab only in the case of errors
